### ISSUE TITLE
Using reflection to get tweakables

### ISSUE THREAD

**Issue by canisin** [jfrouleau/PreciseEditor#1]
Heya there,

Just saw your mod featured in Kottabos' video and loved it! Needless to say, I hate fiddling with gizmos and sliders when I am trying to arrive at a precise value.

I was particularly curious when I saw that the mod also allows precise editing of tweakable values. So I went and immediately checked to see how you determined what tweakable values are available on a part. I was surprised to see that you had a static dictionary to set them.

I cannot currently contribute code for this, but being a professional c# programmer and having looked at some addon codes for KSP, I believe that you can probably collect that information via some use of reflection and/or attributes.

As far as I understand it tweakables are fields of KSPModule classes that are marked with the KSPField attribute and with the value IsGuiActive set to true. You should be able to use this information to track all available tweakables on all parts and all mods!

**Comment by jfrouleau** [comment]
Hi,
I'm glad you like the mod and thank you for your comment. Listing dynamically all tweakables would be nice but I restricted the list on purpose because some of them cannot accept any value. For example, setting the number of fairing sides to 100 will display the fairing incorrectly in flight. I would need to have for each field an acceptable range of values for validation.

**Comment by canisin** [comment]
Hmm... chances are that information is also relayed by the module class to the game code in some way that you can intercept. Very probably via the same attribute. Let me see if i can spend some time this afternoon digging for some examples :)

**Comment by canisin** [comment]
I have looked through github repositories of a couple of famous mods and found the following:

In the following files, you will see that the attribute KSPField is used along with the attribute UI_FloatRange to set the min, max and step values for float fields that have guiActive or guiActiveEditor.

https://github.com/BobPalmer/Konstruction/blob/master/Source/Konstruction/Konstruction/ModuleWeldablePort.cs

https://github.com/ChrisAdderley/near-future/blob/master/DischargeCapacitor.cs (lines 85-90)
https://github.com/BobPalmer/Konstruction/blob/master/Source/Konstruction/Konstruction/ModuleWeldablePort.cs (lines 67-80)

In the last file there is also a bool KSPField with UI_Toggle but I guess that is irrelevant for your mod.

Let me know if you are able to make use of these attributes to query tweakables dynamically.

Kind regards,
Can

**Comment by jfrouleau** [comment]
Thanks for the information. I will certainly take a look at it next time I will have time to work on the mod and give it a try. I'll let you know how it goes.

**Comment by jfrouleau** [comment]
I tried a KSP installation with a few others mods along Precise Editor and discovered that it produced and error because a part was using a part module with a different name. So apparently mods can extend stock part modules and have a different name if I understand. So the fix you propose is really necessary.

However I'm a rookie in C# and have a difficult time figuring out how to do this. I barely know what an attribute is and how it works. I found ModuleAttributes in class PartModule and then I'm stuck. I don't know how to get KSPFields from there If you have some time, I could use some help.

Thank you,
jfrouleau

**Comment by canisin** [comment]
Hello there,

I am going to get you a pull request about this soon! :)

Kind regards,
Can

**Comment by canisin** [comment]
Hey again,

I have just created a pull request that should handle the task of collecting tweakables from part modules via reflection. 

There are two important todo's in TweakablePartModules.cs. The one about localization should be easy enough, just try running the game with the updated code and see if any field labels contain localization codes, if they do, you should probably use Localizer.Format on KSPField.guiName.

The second one is more interesting and makes better use of all these changes. Currently I could not see any limit checking on the tweakable values. But now that we have a hold of the UI_FloatRange attribute we should be able to use its min/max fields to limit the interface.

Third, your hardcoded method was sort of a whitelist where you allowed only known fields to be tweaked via the interface. Now with my pull request any float KSPField should be tweakable but this time we might to implement some kind of blacklist if unwanted tweakables start showing up on the interface.

PS: Having looked at the add on code I would not at all consider you a C# rookie! Not at all.. :) 

Kind regards, and keep me posted! I don't have any time to play the game and test these changes myself so I am looking forward to news from you!
Can

**Comment by jfrouleau** [comment]
Thank you for the pull request ! I will check that out very soon. Sorry for the delay, I don't always have time for KSP modding with a full time job and other life things ;-) Also I just fixed an important mirror rotation symmetry bug which I wanted to address first. Bug fix before new features is my motto (Hello Squad!).

It's true that this is my first C# project but I have 8 years experience as a game programmer with C and now 2.5 years as a web programmer so I suppose it shows a little. :-)

**Comment by jfrouleau** [comment]
Hi canisin, I tried the mod with your modifications on tweakables and it works...partially. It looks like decouplers force percent and engines thrust limiter are listed but not the other tweakables. For exemple I noted the following are missing: gimbal limit, deploy limit, wheel authority, authority limiter, friction control, drive limiter and traction control.

**Comment by jfrouleau** [comment]
Okay I managed to find why some tweakable were missing. On line 54 I removed the following condition and everything is perfect ! I merged the branch.
&& a.kspFieldInfo.guiActiveEditor

**Comment by canisin** [comment]
hmm that condition was supposed to distinguish between possible internal fields and those that are actually accessible and visible in the gui (as the name suggests).
can you maybe repeat your test while bringing back the condition and checking whether you have the advanced tweakables option set to true in your game settings?

**Comment by jfrouleau** [comment]
Yes the advanced tweakables are on. If I right click lets say on an engine the gimbal limit is listed but not in Precise Editor. Then I tested with advanced tweakables off and it removed the actuation toggles not the gimbal limit so these must not be advanced tweakables. I also tried with a.kspFieldInfo.guiActive and they're still some tweakables missing.

**Comment by jfrouleau** [comment]
Also, just want to let you know that the todo tasks are done (RangeInfo and Localization) and it's working very well.
