### ISSUE TITLE
no auto update of position

### ISSUE THREAD

**Issue by menachg** [jfrouleau/PreciseEditor#6]
it used to be that if I selected a location/rotation property (ie x y or z) and the selected another part it would update that property to be the same on the other property
I really liked it as it allowed me to quickly edit multiple parts to be in the same position
what happened to the feature?
when did it got dropped and how can I re-add it
thanks really in advanced

**Comment by jfrouleau** [comment]
It is a bug that I found and fixed. It was never intended to be that way. The problem is it was changing parts just by selecting them which is not always what people want. What I do in your case is just select the text and do a copy-paste with ctrl-c, ctrl-v in other fields.

**Comment by menachg** [comment]
how much work is to add this as an optional feature?

**Comment by jfrouleau** [comment]
Aligning a part with another part on a given axis is very easy. It is the UI which I'm not sure about. This is a multi-part operation and we can only select one part at a time.
