### ISSUE TITLE
When Config File is Updated, it caused MM cache to rebuild

### ISSUE THREAD

**Issue by Joker58th** [jfrouleau/PreciseEditor#7]
I think you need to store the config file in a folder called PluginData.  Many other mods do this.  I've noticed my MM cache getting rebuilt more often and the log points to your config file as the culprit.  

Love the mod, thanks!

**Comment by jfrouleau** [comment]
Thanks, I didn't know about that. I will check this out.

**Comment by jfrouleau** [comment]
The fix is commited in the master branch and will be included in the next release.

**Comment by jfrouleau** [comment]
Precise Editor 1.3.3 is released with the fix.

**Comment by Joker58th** [comment]
Excellent! Thank you.

**Comment by jfrouleau** [comment]
I'm curious. Did that solved your MM cache issue ?

**Comment by Joker58th** [comment]
Just tested this specifically.  Yes!  Solves it.  No cache rebuild after making a change to the values in your mod.  Thanks again!  And thanks for making the values stick.  I remember them resetting each time in an earlier version.
