### ISSUE TITLE
Changes to angle are acting weird

### ISSUE THREAD

**Issue by AtomicBlastPony** [jfrouleau/PreciseEditor#8]
Whenever I try to change a 90 degree angle to 91 degrees, it changes to 89.0003, when I try to change that back to 90 it changes to 89.995 or something, and if I keep trying to make it 91 it just keeps decreasing by just short of 1 degree. Eventually I end up with a number like 63.4449 or something, all while typing in nothing but 91. The mode is set to absolute.

**Comment by jfrouleau** [comment]
Yes I know it's weird. The way it works is the orientation of the object is expressed using Euler angles. Each time the object is rotated, Unity recalculate the rotation on each axis that give the current orientation. If you apply in the correct sequence the 3 angles shown you will end up with the correct orientation. In short this is the angles given by Unity after rotation and if I would like to keep the previous values for the unmodifed axis it would be way more complicated.

https://en.wikipedia.org/wiki/Euler_angles

**Comment by AtomicBlastPony** [comment]
...explain like I'm 5, please.

**Comment by jfrouleau** [comment]
The angle values that you see after rotation are provided by Unity.

**Comment by AtomicBlastPony** [comment]
So only the displayed values are scewed up, and not the actual part rotation? Thanks.
